# Generated by Django 3.1.5 on 2021-01-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_curr', models.CharField(max_length=5, verbose_name='Валюта 1')),
                ('first_qnt', models.CharField(max_length=65, verbose_name='Кол-во 1')),
                ('second_curr', models.CharField(max_length=5, verbose_name='Валюта 1')),
                ('second_qnt', models.CharField(max_length=65, verbose_name='Кол-во 2')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
